# Project Metadata
sonar.projectKey=youssef-abbih_go-todo-list-api
sonar.organization=youssef-abbih
sonar.projectName=youssef-abbih/go-todo-list-api

# Source and Test Configurations
sonar.sources=.
sonar.tests=.

# Include only actual source code for coverage analysis
sonar.inclusions=**/*.go

# Explicitly define what files are test files
sonar.test.inclusions=**/*_test.go

# Exclusions
sonar.exclusions=docs/**, .go-cache/**, **/*_test.go, main.go, models/init.go, deployment/**

# Coverage Report Path
sonar.go.coverage.reportPaths=coverage.out
sonar.go.version=1.24