sonar.projectKey=youssef-abbih_go-todo-list-api
sonar.organization=youssef-abbih
sonar.projectName=go-todo-list-api

sonar.sources=.
sonar.inclusions=**/*.go
sonar.exclusions=docs/**,.go-cache/**,**/*_test.go,main.go,models/init.go,deployment/**

sonar.go.coverage.reportPaths=coverage.out
sonar.go.version=1.24